//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL_CNPM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IDPro { get; set; }
        public string ProName { get; set; }
        public int Pro_Quantity { get; set; }
        public string Pro_Des { get; set; }
        public string Pro_Image { get; set; }
        public Nullable<int> IdCate { get; set; }
        public string Pro_Price { get; set; }
    }
}
